In [ ]:

#   Drafts: 2000-2015
#   Position: QB
#   Appeared in a minimum of 9 games 

#   100 total players in the population

In [2]:
#dependencies

import pandas as pd
import csv

In [3]:
#read in statistics files

file_2000 = "../mica_resources/2000_passing.csv"
file_2000_df = pd.read_csv(file_2000)

file_2001 = "../mica_resources/2001_passing.csv"
file_2001_df = pd.read_csv(file_2001)

file_2002 = "../mica_resources/2002_passing.csv"
file_2002_df = pd.read_csv(file_2002)

file_2003 = "../mica_resources/2003_passing.csv"
file_2003_df = pd.read_csv(file_2003)

file_2004 = "../mica_resources/2004_passing.csv"
file_2004_df = pd.read_csv(file_2004)

file_2005 = "../mica_resources/2005_passing.csv"
file_2005_df = pd.read_csv(file_2005)

file_2006 = "../mica_resources/2006_passing.csv"
file_2006_df = pd.read_csv(file_2006)

file_2007 = "../mica_resources/2007_passing.csv"
file_2007_df = pd.read_csv(file_2001)

file_2008 = "../mica_resources/2008_passing.csv"
file_2008_df = pd.read_csv(file_2008)

file_2009 = "../mica_resources/2009_passing.csv"
file_2009_df = pd.read_csv(file_2009)

file_2010 = "../mica_resources/2010_passing.csv"
file_2010_df = pd.read_csv(file_2010)

file_2011 = "../mica_resources/2011_passing.csv"
file_2011_df = pd.read_csv(file_2011)

file_2012 = "../mica_resources/2012_passing.csv"
file_2012_df = pd.read_csv(file_2012)

file_2013 = "../mica_resources/2013_passing.csv"
file_2013_df = pd.read_csv(file_2013)

file_2014 = "../mica_resources/2014_passing.csv"
file_2014_df = pd.read_csv(file_2014)

file_2015 = "../mica_resources/2015_passing.csv"
file_2015_df = pd.read_csv(file_2015)

file_2016 = "../mica_resources/2016_passing.csv"
file_2016_df = pd.read_csv(file_2016)

file_2017 = "../mica_resources/2017_passing.csv"
file_2017_df = pd.read_csv(file_2017)

file_2018 = "../mica_resources/2018_passing.csv"
file_2018_df = pd.read_csv(file_2018)

file_2019 = "../mica_resources/2019_passing.csv"
file_2019_df = pd.read_csv(file_2019)

file_2020 = "../mica_resources/2020_passing.csv"
file_2020_df = pd.read_csv(file_2020)

In [37]:
#contcatonate all stats files into one

full_statistics_df = pd.concat([file_2000_df, file_2001_df, file_2002_df,file_2003_df, file_2004_df, file_2005_df, file_2006_df, file_2007_df, file_2008_df, file_2009_df, file_2010_df, file_2011_df, file_2012_df, file_2013_df, file_2014_df, file_2015_df, file_2016_df, file_2017_df,file_2018_df, file_2019_df, file_2020_df])

,Rk,Player,Tm,Age,Pos,G,GS,QBrec,Cmp,Att,...,Y/G,Rate,Sk,Yds.1,Sk%,NY/A,ANY/A,4QC,GWD,QBR
0,1,Peyton Manning*,IND,24,QB,16,16,10/6/2000,357,571,...,275.8,94.7,20.0,131.0,3.4,7.25,7.22,2.0,3.0,NaN
1,2,Jeff Garcia*,SFO,30,QB,16,16,6/10/2000,355,561,...,267.4,97.6,24.0,155.0,4.1,7.05,7.34,NaN,NaN,NaN
2,3,Elvis Grbac*,KAN,30,QB,15,15,7/8/2000,326,547,...,277.9,89.9,29.0,213.0,5.0,6.87,6.75,3.0,3.0,NaN
3,4,Daunte Culpepper*,MIN,23,QB,16,16,11/5/2000,297,474,...,246.1,98.0,34.0,181.0,6.7,7.39,7.28,3.0,4.0,NaN
4,5,Brett Favre,GNB,31,QB,16,16,9/7/2000,338,580,...,238.3,78.0,33.0,236.0,5.4,5.83,5.31,0.0,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,108,Brett Kern,TEN,34,QB,13,0,NaN,0,1,...,0.0,39.6,0.0,0.0,0.0,0.00,0.00,NaN,NaN,0.0
108,109,D.J. Moore,CAR,23,QB,15,14,NaN,0,1,...,0.0,39.6,0.0,0.0,0.0,0.00,0.00,NaN,NaN,NaN
109,110,Zach Pascal,IND,26,QB,16,14,NaN,0,1,...,0.0,39.6,0.0,0.0,0.0,0.00,0.00,NaN,NaN,1.8
110,111,Sammy Watkins,KAN,27,QB,10,9,NaN,0,1,...,0.0,0.0,0.0,0.0,0.0,0.00,-45.00,NaN,NaN,0.0
111,112,Isaiah Wright,WAS,23,QB,14,6,NaN,0,1,...,0.0,39.6,0.0,0.0,0.0,0.00,0.00,NaN,NaN,2.8

In [111]:
##read to csv for changes easier to make in excel

full_statistics_df.to_csv("Output/full_statistics.csv", index=False, header=True)

##bring back from Excel

updated_full_statistics = "Output/full_stats.csv"
updated_full_statistics_df = pd.read_csv(updated_full_statistics)

##read in qb_population csv and grab list of 100 qb's

qb_population = "drafts_qb_only_all_years.csv"
qb_population_df = pd.read_csv(qb_population)

qb_100_list = qb_population_df["Player"].tolist()

##remove qb's not in our qb_100_list and set index to Player

qb_statistics_df = updated_full_statistics_df[updated_full_statistics_df.Player.isin(qb_100_list)].set_index('Player')

In [114]:
##print stats for our 100 qbs thru 2020

qb_statistics_df

,season_year,Tm,Age,Pos,G,GS,QBrec,Cmp,Att,Cmp%,...,Y/G,Rate,Sk,Yds.1,Sk%,NY/A,ANY/A,4QC,GWD,QBR
Player,,,,,,,,,,,,,,,,,,,,,
Spergon Wynn,2000,CLE,22,QB,7,1,0-1-0,22,54,40.7,...,23.9,41.2,13.0,89.0,19.4,1.16,0.49,NaN,NaN,NaN
Chad Pennington,2000,NYJ,24,QB,1,0,NaN,2,5,40.0,...,67.0,127.1,1.0,4.0,16.7,10.50,13.83,NaN,NaN,NaN
Chris Redman,2000,BAL,23,QB,2,0,NaN,2,3,66.7,...,9.5,84.0,0.0,0.0,0.0,6.33,6.33,NaN,NaN,NaN
Tom Brady,2000,NWE,23,QB,1,0,NaN,1,3,33.3,...,6.0,42.4,0.0,0.0,0.0,2.00,2.00,NaN,NaN,NaN
Tim Rattay,2000,SFO,23,QB,1,0,NaN,1,1,100.0,...,-4.0,79.2,0.0,0.0,0.0,-4.00,-4.00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tyrod Taylor,2020,LAC,31,QB,2,1,1-0-0,16,30,53.3,...,104.0,75.4,2.0,1.0,6.3,6.47,6.47,1.0,1.0,16.6
Jameis Winston,2020,NOR,26,QB,4,0,NaN,7,11,63.6,...,18.8,83.5,2.0,11.0,15.4,4.92,4.92,NaN,NaN,12.0
Geno Smith,2020,SEA,30,QB,1,0,NaN,4,5,80.0,...,33.0,94.2,1.0,3.0,16.7,5.00,5.00,NaN,NaN,3.9
Logan Thomas,2020,WAS,29,QB,16,15,NaN,1,1,100.0,...,1.8,118.7,0.0,0.0,0.0,28.00,28.00,NaN,NaN,40.1
A.J. McCarron,2020,HOU,30,QB,2,0,NaN,1,1,100.0,...,10.0,118.7,1.0,12.0,50.0,4.00,4.00,NaN,NaN,0.0